"use client";

import html2canvas from "html2canvas";

export default async function exportPDF(summary, timeline, type, goalType) {

  const html2pdf = (await import("html2pdf.js")).default;

  const chartElement = document.getElementById("pieChartContainer");

  let chartImage = "";

  if (chartElement) {
    const canvas = await html2canvas(chartElement, { scale: 2 });
    chartImage = canvas.toDataURL("image/png");
  }

  const container = document.createElement("div");

  container.style.width = "190mm";   // fit A4 width
  container.style.margin = "auto";
  container.style.fontFamily = "Arial";
  container.style.padding = "20px";

  container.innerHTML = `
  <div>

    <div style="border-bottom:3px solid #224c87;padding-bottom:10px;margin-bottom:20px">

      <h1 style="margin:0;color:#224c87">FinVision</h1>
      <p style="margin:0;font-size:14px">Goal Planning Report</p>

    </div>

    <h2>Goal: ${goalType}</h2>

    <h3 style="margin-top:20px">Investment Summary</h3>

    <table style="width:100%;margin-bottom:20px;font-size:14px">

      <tr>
        <td><b>Future Goal Value</b></td>
        <td>₹${summary.futureValue.toLocaleString()}</td>
      </tr>

      <tr>
        <td><b>Monthly SIP Required</b></td>
        <td>₹${summary.monthlySIP.toLocaleString()}</td>
      </tr>

      <tr>
        <td><b>Total Invested</b></td>
        <td>₹${summary.totalInvested.toLocaleString()}</td>
      </tr>

      <tr>
        <td><b>Estimated Profit</b></td>
        <td style="color:#16a34a;font-weight:bold">
          ₹${summary.profit.toLocaleString()}
        </td>
      </tr>

    </table>


    <h3 style="text-align:center">Investment Distribution</h3>

    <div style="text-align:center;margin-bottom:10px">
      <img src="${chartImage}" style="width:240px"/>
    </div>

    <div style="text-align:center;font-size:14px;margin-bottom:20px">

      <p><b>Invested Amount:</b> ₹${summary.totalInvested.toLocaleString()}</p>
      <p><b>Returns Earned:</b> ₹${summary.profit.toLocaleString()}</p>

    </div>


    <h3>${type} Timeline</h3>

    <table style="width:100%;border-collapse:collapse;font-size:13px">

      <thead>
        <tr style="background:#f3f4f6">

          <th style="border:1px solid #ccc;padding:6px">Period</th>
          <th style="border:1px solid #ccc;padding:6px">Invested</th>
          <th style="border:1px solid #ccc;padding:6px">Interest</th>
          <th style="border:1px solid #ccc;padding:6px">Total Invested</th>
          <th style="border:1px solid #ccc;padding:6px">Portfolio Value</th>
          <th style="border:1px solid #ccc;padding:6px">Profit</th>

        </tr>
      </thead>

      <tbody>

        ${timeline.map(row => `
        <tr>

          <td style="border:1px solid #ccc;padding:6px">${row.period}</td>

          <td style="border:1px solid #ccc;padding:6px">
            ₹${row.invested.toLocaleString()}
          </td>

          <td style="border:1px solid #ccc;padding:6px">
            ₹${row.interest.toLocaleString()}
          </td>

          <td style="border:1px solid #ccc;padding:6px">
            ₹${row.totalInvested.toLocaleString()}
          </td>

          <td style="border:1px solid #ccc;padding:6px">
            ₹${row.value.toLocaleString()}
          </td>

          <td style="border:1px solid #ccc;padding:6px;color:#16a34a">
            ₹${row.profit.toLocaleString()}
          </td>

        </tr>
        `).join("")}

      </tbody>

    </table>

    <p style="margin-top:25px;font-size:11px;color:#666;text-align:center">
      This report is generated by FinVision for financial planning purposes only.
    </p>

  </div>
  `;

  html2pdf()
    .from(container)
    .set({
      margin: 10,
      filename: `FinVision_${type}_Report.pdf`,
      html2canvas: { scale: 2 },
      jsPDF: {
        unit: "mm",
        format: "a4",
        orientation: "portrait"
      }
    })
    .save();
}